# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87b2c30e56aa1dda1f6ba1a080cbd8f299bdaef1521ac0b5716e9e7f40ff003b4100bc42e9a2476f6102be2d0187e8f85ecb67f0554b3b5207552bc2e8c316ba

test:
  secret_key_base: 2682b720a5010eace4e102ac2b87c86c2c191688cd446ba1fd2e6fb467575f0baa35d58849dc61aed84abb8915bd9352a1c2b12ef9f15b6ebf96ad70e368cd93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
